xcodebuild_arguments:
  - -scheme
  - Lark
module: Lark
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../Lark-Docs/master
clean: true
github_url: https://github.com/Bouke/Lark
dash_url: http://boukehaarsma.nl/Lark/Lark.xml
