xcodebuild_arguments:
  - -scheme
  - Lark
module: Lark
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../Lark-Docs/master
clean: true
github_url: https://github.com/Bouke/Lark
dash_url: http://boukehaarsma.nl/Lark/Lark.xml
custom_categories:
  - name: Client
    children:
      - Client
      - Envelope
      - Header
      - Fault
  - name: Serialization
    children:
      - HeaderSerializable
      - StringSerializable
      - StringSerializableList
      - StringDeserializable
      - XMLSerializable
      - XMLDeserializable
      - XMLSerializationError
      - XMLDeserializationError
  - name: Base Types
    children:
      - Bool
      - Data
      - Date
      - Decimal
      - Double
      - Float
      - Int
      - Int8
      - Int16
      - Int32
      - Int64
      - String
      - UInt8
      - UInt16
      - UInt32
      - UInt64
      - URL
  - name: Extensions
    children:
      - Result
  - name: XML Tooling
    children:
      - NS_SOAP
      - NS_XSI
      - QualifiedName
      - XMLElement
      - XMLNode
