disabled_rules:
  - colon
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - line_length
  - opening_brace
  - todo
  - type_name
  - variable_name
included:
  - Sources
  - Tests
cyclomatic_complexity:
  warning: 25
  error: 50
