// This file was generated by Lark. https://github.com/Bouke/Lark

import Foundation
import LarkRuntime

//
// MARK: - SOAP Structures
//
class SayNothingType: XMLDeserializable {
    init() {
    }
    required init(deserialize element: XMLElement) throws {
    }
    func serialize(_ element: XMLElement) throws {
    }
}

class SayNothing: SayNothingType {
    override init() {
        super.init()
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

enum PartOfDay: String, XMLSerializable, XMLDeserializable {
    case afternoon = "afternoon"
    case evening = "evening"
    case morning = "morning"
    case night = "night"
    init(deserialize element: XMLElement) throws {
        self.init(rawValue: element.stringValue!)!
    }
    func serialize(_ element: XMLElement) throws {
        element.stringValue = self.rawValue
    }
}

class StringArrayType: XMLDeserializable {
    let string: [String]
    init(string: [String]) {
        self.string = string
    }
    required init(deserialize element: XMLElement) throws {
        self.string = try element.elements(forLocalName: "string", uri: "spyne.examples.hello").map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        for item in string {
            let itemNode = try element.createElement(localName: "string", uri: "spyne.examples.hello")
            try item.serialize(itemNode)
            element.addChild(itemNode)
        }
    }
}

class StringArray: StringArrayType {
    override init(string: [String]) {
        super.init(string: string)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayMaybeSomethingResponseType: XMLDeserializable {
    let sayMaybeSomethingResult: String?
    init(sayMaybeSomethingResult: String?) {
        self.sayMaybeSomethingResult = sayMaybeSomethingResult
    }
    required init(deserialize element: XMLElement) throws {
        self.sayMaybeSomethingResult = try element.elements(forLocalName: "say_maybe_somethingResult", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let sayMaybeSomethingResult = sayMaybeSomethingResult {
            let sayMaybeSomethingResultNode = try element.createElement(localName: "say_maybe_somethingResult", uri: "spyne.examples.hello")
            try sayMaybeSomethingResult.serialize(sayMaybeSomethingResultNode)
            element.addChild(sayMaybeSomethingResultNode)
        }
    }
}

class SayMaybeSomethingType: XMLDeserializable {
    let name: String?
    init(name: String?) {
        self.name = name
    }
    required init(deserialize element: XMLElement) throws {
        self.name = try element.elements(forLocalName: "name", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let name = name {
            let nameNode = try element.createElement(localName: "name", uri: "spyne.examples.hello")
            try name.serialize(nameNode)
            element.addChild(nameNode)
        }
    }
}

class SayMaybeSomething: SayMaybeSomethingType {
    override init(name: String?) {
        super.init(name: name)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayMaybeSomethingResponse: SayMaybeSomethingResponseType {
    override init(sayMaybeSomethingResult: String?) {
        super.init(sayMaybeSomethingResult: sayMaybeSomethingResult)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class PartOfDayArrayType: XMLDeserializable {
    let partOfDay: [PartOfDay]
    init(partOfDay: [PartOfDay]) {
        self.partOfDay = partOfDay
    }
    required init(deserialize element: XMLElement) throws {
        self.partOfDay = try element.elements(forLocalName: "PartOfDay", uri: "spyne.examples.hello").map(PartOfDay.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        for item in partOfDay {
            let itemNode = try element.createElement(localName: "PartOfDay", uri: "spyne.examples.hello")
            try item.serialize(itemNode)
            element.addChild(itemNode)
        }
    }
}

class PartOfDayArray: PartOfDayArrayType {
    override init(partOfDay: [PartOfDay]) {
        super.init(partOfDay: partOfDay)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class GreetResponse: GreetResponseType {
    override init(greetResult: String?) {
        super.init(greetResult: greetResult)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayMaybeNothingType: XMLDeserializable {
    let name: String?
    init(name: String?) {
        self.name = name
    }
    required init(deserialize element: XMLElement) throws {
        self.name = try element.elements(forLocalName: "name", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let name = name {
            let nameNode = try element.createElement(localName: "name", uri: "spyne.examples.hello")
            try name.serialize(nameNode)
            element.addChild(nameNode)
        }
    }
}

class SayMaybeNothingResponseType: XMLDeserializable {
    let sayMaybeNothingResult: String?
    init(sayMaybeNothingResult: String?) {
        self.sayMaybeNothingResult = sayMaybeNothingResult
    }
    required init(deserialize element: XMLElement) throws {
        self.sayMaybeNothingResult = try element.elements(forLocalName: "say_maybe_nothingResult", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let sayMaybeNothingResult = sayMaybeNothingResult {
            let sayMaybeNothingResultNode = try element.createElement(localName: "say_maybe_nothingResult", uri: "spyne.examples.hello")
            try sayMaybeNothingResult.serialize(sayMaybeNothingResultNode)
            element.addChild(sayMaybeNothingResultNode)
        }
    }
}

class SayMaybeNothingResponse: SayMaybeNothingResponseType {
    override init(sayMaybeNothingResult: String?) {
        super.init(sayMaybeNothingResult: sayMaybeNothingResult)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayNothingResponseType: XMLDeserializable {
    init() {
    }
    required init(deserialize element: XMLElement) throws {
    }
    func serialize(_ element: XMLElement) throws {
    }
}

class SayNothingResponse: SayNothingResponseType {
    override init() {
        super.init()
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayMaybeNothing: SayMaybeNothingType {
    override init(name: String?) {
        super.init(name: name)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class GreetResponseType: XMLDeserializable {
    let greetResult: String?
    init(greetResult: String?) {
        self.greetResult = greetResult
    }
    required init(deserialize element: XMLElement) throws {
        self.greetResult = try element.elements(forLocalName: "greetResult", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let greetResult = greetResult {
            let greetResultNode = try element.createElement(localName: "greetResult", uri: "spyne.examples.hello")
            try greetResult.serialize(greetResultNode)
            element.addChild(greetResultNode)
        }
    }
}

class SayHelloResponseType: XMLDeserializable {
    let sayHelloResult: StringArrayType
    init(sayHelloResult: StringArrayType) {
        self.sayHelloResult = sayHelloResult
    }
    required init(deserialize element: XMLElement) throws {
        self.sayHelloResult = try StringArrayType(deserialize: element.elements(forLocalName: "say_helloResult", uri: "spyne.examples.hello").first!)
    }
    func serialize(_ element: XMLElement) throws {
        let sayHelloResultNode = try element.createElement(localName: "say_helloResult", uri: "spyne.examples.hello")
        try sayHelloResult.serialize(sayHelloResultNode)
        element.addChild(sayHelloResultNode)
    }
}

class SayHelloResponse: SayHelloResponseType {
    override init(sayHelloResult: StringArrayType) {
        super.init(sayHelloResult: sayHelloResult)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class SayHelloType: XMLDeserializable {
    let name: String?
    let times: Int?
    init(name: String?, times: Int?) {
        self.name = name
        self.times = times
    }
    required init(deserialize element: XMLElement) throws {
        self.name = try element.elements(forLocalName: "name", uri: "spyne.examples.hello").first.map(String.init(deserialize:))
        self.times = try element.elements(forLocalName: "times", uri: "spyne.examples.hello").first.map(Int.init(deserialize:))
    }
    func serialize(_ element: XMLElement) throws {
        if let name = name {
            let nameNode = try element.createElement(localName: "name", uri: "spyne.examples.hello")
            try name.serialize(nameNode)
            element.addChild(nameNode)
        }
        if let times = times {
            let timesNode = try element.createElement(localName: "times", uri: "spyne.examples.hello")
            try times.serialize(timesNode)
            element.addChild(timesNode)
        }
    }
}

class SayHello: SayHelloType {
    override init(name: String?, times: Int?) {
        super.init(name: name, times: times)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

class GreetType: XMLDeserializable {
    let partOfDay: PartOfDay?
    let partOfDays: PartOfDayArrayType
    init(partOfDay: PartOfDay?, partOfDays: PartOfDayArrayType) {
        self.partOfDay = partOfDay
        self.partOfDays = partOfDays
    }
    required init(deserialize element: XMLElement) throws {
        self.partOfDay = try element.elements(forLocalName: "part_of_day", uri: "spyne.examples.hello").first.map(PartOfDay.init(deserialize:))
        self.partOfDays = try PartOfDayArrayType(deserialize: element.elements(forLocalName: "part_of_days", uri: "spyne.examples.hello").first!)
    }
    func serialize(_ element: XMLElement) throws {
        if let partOfDay = partOfDay {
            let partOfDayNode = try element.createElement(localName: "part_of_day", uri: "spyne.examples.hello")
            try partOfDay.serialize(partOfDayNode)
            element.addChild(partOfDayNode)
        }
        let partOfDaysNode = try element.createElement(localName: "part_of_days", uri: "spyne.examples.hello")
        try partOfDays.serialize(partOfDaysNode)
        element.addChild(partOfDaysNode)
    }
}

class Greet: GreetType {
    override init(partOfDay: PartOfDay?, partOfDays: PartOfDayArrayType) {
        super.init(partOfDay: partOfDay, partOfDays: partOfDays)
    }
    required init(deserialize element: XMLElement) throws {
        try super.init(deserialize: element)
    }
    override func serialize(_ element: XMLElement) throws {
        try super.serialize(element)
    }
}

//
// MARK: - SOAP Client
//
class HelloWorldServiceClient: Client {
    override init() {
    }
    func sayNothing(sayNothing: SayNothing) throws -> SayNothingResponse {
        var parameters = [XMLElement]()
        let sayNothingNode = XMLElement(prefix: "ns0", localName: "say_nothing", uri: "spyne.examples.hello")
        sayNothingNode.addNamespace(XMLNode.namespace(withName: "ns0", stringValue: "spyne.examples.hello") as! XMLNode)
        try sayNothing.serialize(sayNothingNode)
        parameters.append(sayNothingNode)
        let body = try send(parameters: parameters)
        let outputNode = body.elements(forLocalName: "say_nothingResponse", uri: "spyne.examples.hello").first!
        return try SayNothingResponse(deserialize: outputNode)
    }
    func sayMaybeSomething(sayMaybeSomething: SayMaybeSomething) throws -> SayMaybeSomethingResponse {
        var parameters = [XMLElement]()
        let sayMaybeSomethingNode = XMLElement(prefix: "ns0", localName: "say_maybe_something", uri: "spyne.examples.hello")
        sayMaybeSomethingNode.addNamespace(XMLNode.namespace(withName: "ns0", stringValue: "spyne.examples.hello") as! XMLNode)
        try sayMaybeSomething.serialize(sayMaybeSomethingNode)
        parameters.append(sayMaybeSomethingNode)
        let body = try send(parameters: parameters)
        let outputNode = body.elements(forLocalName: "say_maybe_somethingResponse", uri: "spyne.examples.hello").first!
        return try SayMaybeSomethingResponse(deserialize: outputNode)
    }
    func sayHello(sayHello: SayHello) throws -> SayHelloResponse {
        var parameters = [XMLElement]()
        let sayHelloNode = XMLElement(prefix: "ns0", localName: "say_hello", uri: "spyne.examples.hello")
        sayHelloNode.addNamespace(XMLNode.namespace(withName: "ns0", stringValue: "spyne.examples.hello") as! XMLNode)
        try sayHello.serialize(sayHelloNode)
        parameters.append(sayHelloNode)
        let body = try send(parameters: parameters)
        let outputNode = body.elements(forLocalName: "say_helloResponse", uri: "spyne.examples.hello").first!
        return try SayHelloResponse(deserialize: outputNode)
    }
    func greet(greet: Greet) throws -> GreetResponse {
        var parameters = [XMLElement]()
        let greetNode = XMLElement(prefix: "ns0", localName: "greet", uri: "spyne.examples.hello")
        greetNode.addNamespace(XMLNode.namespace(withName: "ns0", stringValue: "spyne.examples.hello") as! XMLNode)
        try greet.serialize(greetNode)
        parameters.append(greetNode)
        let body = try send(parameters: parameters)
        let outputNode = body.elements(forLocalName: "greetResponse", uri: "spyne.examples.hello").first!
        return try GreetResponse(deserialize: outputNode)
    }
    func sayMaybeNothing(sayMaybeNothing: SayMaybeNothing) throws -> SayMaybeNothingResponse {
        var parameters = [XMLElement]()
        let sayMaybeNothingNode = XMLElement(prefix: "ns0", localName: "say_maybe_nothing", uri: "spyne.examples.hello")
        sayMaybeNothingNode.addNamespace(XMLNode.namespace(withName: "ns0", stringValue: "spyne.examples.hello") as! XMLNode)
        try sayMaybeNothing.serialize(sayMaybeNothingNode)
        parameters.append(sayMaybeNothingNode)
        let body = try send(parameters: parameters)
        let outputNode = body.elements(forLocalName: "say_maybe_nothingResponse", uri: "spyne.examples.hello").first!
        return try SayMaybeNothingResponse(deserialize: outputNode)
    }
}

